<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23229" started-at="2020-06-08T04:48:40Z" finished-at="2020-06-08T04:49:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23229" started-at="2020-06-08T04:48:40Z" finished-at="2020-06-08T04:49:03Z">
      <class name="com.w2a.testcases.EcommerceTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.w2a.testcases.EcommerceTest@2f686d1f]" name="beforeTest" is-config="true" duration-ms="4022" started-at="2020-06-08T04:48:40Z" finished-at="2020-06-08T04:48:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="addtoCartTest()[pri:0, instance:com.w2a.testcases.EcommerceTest@2f686d1f]" name="addtoCartTest" duration-ms="19192" started-at="2020-06-08T04:48:44Z" finished-at="2020-06-08T04:49:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.w2a.pages.EkartPage1.AddtoCart(EkartPage1.java:43)
at com.w2a.testcases.EcommerceTest.addtoCartTest(EcommerceTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addtoCartTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.w2a.testcases.EcommerceTest@2f686d1f]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-08T04:49:03Z" finished-at="2020-06-08T04:49:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.w2a.testcases.EcommerceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
